### PR TITLE
Add roost icon, create according webmanifest for mobile view

### PR DESCRIPTION
**Pull request by MikMuellerDev**
### Changes
- general icon for the roost programming language
- icon for the roost playground
- webmanifest file for mobile users
- added icon next to the templates dropdown menu

### CODE REVIEW

**Review by RubixDev — CHANGES_REQUESTED** [review]
First of all, thanks. I would suggest some changes though:

- [ ] If possible, swap the orange and purple in the icon, so that the R is purple and the rooster is orange
- [ ] Remove the icon from the console actionbar again. You would have to tweak all the media queries to account for the extra space needed by the image and I don't like the look of it being there anyways.
- [ ] Add a compressed lower res version of the icon for the favicon
- [ ] Just use the normal icon without the extra play button
- [ ] Put the images in an `images/` subfolder inside the `web/` folder

I will merge this when these changes are implemented

**Review by RubixDev — APPROVED** [review]

**Comment by RubixDev** [comment]
Also, am I free to use the icon in my other projects as well?

**Comment by MikMuellerDev** [comment]
First of all, yes, you are free to use this icon.
Furthermore, I am willing to implement the suggested changes in my fork.

**Comment by MikMuellerDev** [comment]
Just as requested, I am pleased to announce that I've accommodated your changes.

**Comment by RubixDev** [comment]
Perfect! tyvm

**Comment by RubixDev** [comment]
As you can see in commit 47566596270acae326f7dc0ef53e013f99e54a82, I wanted to make the eye of the rooster non-translucent. However, after looking at the commit, I noticed the orange color was slightly different in the source file you uploaded, than in the resulting image. Would you be able to open a new PR with the updated source file and a solid eye?

**Pull request merged**
